### ISSUE TITLE
Lore Selection Bug

### ISSUE THREAD

**Issue by Dan-Nobelium** [jetpropulsioncloud/northgard-analyzer#1]
Hi all,

I cannot select any lores, which prevents me from saving a build, making it impossible to use this program

See attatched screenshots:
<img width="710" height="659" alt="Image" src="https://github.com/user-attachments/assets/b5fd6a3d-3ea1-4605-8a43-08d946107fab" />
<img width="692" height="778" alt="Image" src="https://github.com/user-attachments/assets/7f38c531-9d89-4759-9489-26f84aecd4c7" />
<img width="750" height="1063" alt="Image" src="https://github.com/user-attachments/assets/7bee96e4-fcd4-4420-b82c-7563017f09f6" />

It would be great if the millitary and lore selectores worked, I am running the latest executable on windows 11 if that matters.

**Comment by Dan-Nobelium** [comment]
This issue persists and is not resolved.

I took screenshots to make it clear what the issue is, and would like to know if a replication attempt was made, because at present the app is unusable.

**Comment by Dan-Nobelium** [comment]
If you want anyone to engage with your project, it would be nice if you gave feedback the time of day instead of closing them without comment.

**Comment by blabla666111** [comment]
He did publish a new version yesterday, have you checked it out? Guess thats what "closed" means ;-)

**Comment by Dan-Nobelium** [comment]
> He did publish a new version yesterday, have you checked it out? Guess thats what "closed" means ;-)

Of course I checked the latest build and ensured the issue persisted before replying.

**Comment by jetpropulsioncloud** [comment]
Hi guys! sorry for the delay! I am still new to all of this so please be patient. I have fixed the lore not working but there seems to still be a bug with submission. I have the patch fixed and will push it ASAP! Thank you and apologies again!!!

**Comment by Dan-Nobelium** [comment]
> Hi guys! sorry for the delay! I am still new to all of this so please be patient. I have fixed the lore not working but there seems to still be a bug with submission. I have the patch fixed and will push it ASAP! Thank you and apologies again!!!

Thanks Jet!

**Comment by Dan-Nobelium** [comment]
The latest build has fixed the Lore list and the app is usable, thanks!

<img width="447" height="355" alt="Image" src="https://github.com/user-attachments/assets/05fa7a26-e9cf-45ff-886a-c3a3d6a666ff" />

The Lore tree template does not seem to work ,but thats okay because the predefined lore list works 

<img width="471" height="530" alt="Image" src="https://github.com/user-attachments/assets/63e15fe3-909c-46ba-9777-cb48bb95e3ff" />

**Comment by Dan-Nobelium** [comment]
Sadly it still appears to be broken for Owl

<img width="478" height="458" alt="Image" src="https://github.com/user-attachments/assets/8ac5039a-1dee-4e77-a0ed-c134a27cd475" />

**Comment by Dan-Nobelium** [comment]
Also it looks like the builds cant be edited after the fact, which means a slight tweat would require resubmitting it entirely?
